### ISSUE TITLE
Add feature of converting type to another

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#250]
It would be great to enable configuration to be able to convert a specific type to another. This feature is necessary to improve #239 by generalizing the hard-coded type conversion for a specific binder and 3rd-party library. For example, converting `Eigen::MatrixBase<Derived>` to `Derived` can be done by this feature.

I got the hint from the [README.md](https://github.com/personalrobotics/chimera#configuration) that the authors intended to implement this feature.

Possible configuration would be like this:
```yaml
types:
  # Simple type conversion from 'int' to 'long'
  'int':
    convert_to:
      type: 'long'
  # Convert to a template parameter named 'Derived'. For example, 'Eigen::MatrixBase<Eigen::Matrix3d>' will be converted to 'Eigen::Matrix3d'.
  'template <Derived> class Eigen::MatrixBase':
    convert_to:
      template_parameter: 'Derived'
  # Similar to above but converting to the second parameter type.
  'template<typename NullaryOp, typename PlainObjectType> class Eigen::CwiseNullaryOp':
    convert_to:
      template_parameter: 'PlainObjectType'
```
